insert into songs (Title, Artist, Genre) values ('Rolling in the Deep', 'Emily Johnson', 'blues');
insert into songs (Title, Artist, Genre) values ('Just the Way You Are', 'Sarah Thompson', 'dance');
insert into songs (Title, Artist, Genre) values ('Hallelujah', 'Jessica Martinez', 'r&b');
insert into songs (Title, Artist, Genre) values ('Piano Man', 'Michael Davis', 'pop');
insert into songs (Title, Artist, Genre) values ('Uptown Funk', 'Sarah Thompson', 'latin');
insert into songs (Title, Artist, Genre) values ('Killing Me Softly', 'Jessica Martinez', 'electronic');
insert into songs (Title, Artist, Genre) values ('Uptown Funk', 'Jessica Martinez', 'country');
insert into songs (Title, Artist, Genre) values ('Grenade', 'Olivia Taylor', 'soul');
insert into songs (Title, Artist, Genre) values ('Hallelujah', 'Michael Davis', 'r&b');
insert into songs (Title, Artist, Genre) values ('Every Breath You Take', 'Sarah Thompson', 'rap');
insert into songs (Title, Artist, Genre) values ('No Cry', 'Olivia Taylor', 'pop');
insert into songs (Title, Artist, Genre) values ('Let It Be', 'Michael Davis', 'alternative');
insert into songs (Title, Artist, Genre) values ('I Will Always Love You', 'Jessica Martinez', 'jazz');
insert into songs (Title, Artist, Genre) values ('Bohemian Rhapsody', 'David Wilson', 'alternative');
insert into songs (Title, Artist, Genre) values ('Just the Way You Are', 'David Wilson', 'pop');
insert into songs (Title, Artist, Genre) values ('Every Breath You Take', 'Michael Davis', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Piano Man', 'David Wilson', 'rock');
insert into songs (Title, Artist, Genre) values ('Uptown Funk', 'Sophia Hernandez', 'gospel');
insert into songs (Title, Artist, Genre) values ('Just the Way You Are', 'Michael Davis', 'country');
insert into songs (Title, Artist, Genre) values ('Hallelujah', 'Michael Davis', 'pop');
insert into songs (Title, Artist, Genre) values ('Just the Way You Are', 'Christopher Thomas', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Killing Me Softly', 'Jessica Martinez', 'alternative');
insert into songs (Title, Artist, Genre) values ('Killing Me Softly', 'Olivia Taylor', 'reggae');
insert into songs (Title, Artist, Genre) values ('Grenade', 'Daniel Anderson', 'dance');
insert into songs (Title, Artist, Genre) values ('Let It Be', 'Jessica Martinez', 'punk');
insert into songs (Title, Artist, Genre) values ('Uptown Funk', 'Sophia Hernandez', 'electronic');
insert into songs (Title, Artist, Genre) values ('Piano Man', 'Sarah Thompson', 'reggae');
insert into songs (Title, Artist, Genre) values ('Grenade', 'Sarah Thompson', 'rock');
insert into songs (Title, Artist, Genre) values ('Killing Me Softly', 'Jessica Martinez', 'country');
insert into songs (Title, Artist, Genre) values ('Hallelujah', 'Olivia Taylor', 'gospel');
insert into songs (Title, Artist, Genre) values ('Oops!... I Did It Again', 'Olivia Taylor', 'electronic');
insert into songs (Title, Artist, Genre) values ('I Will Always Love You', 'Michael Davis', 'gospel');
insert into songs (Title, Artist, Genre) values ('Oops!... I Did It Again', 'Sophia Hernandez', 'r&b');
insert into songs (Title, Artist, Genre) values ('Firework', 'Christopher Thomas', 'country');
insert into songs (Title, Artist, Genre) values ('Grenade', 'Christopher Thomas', 'punk');
insert into songs (Title, Artist, Genre) values ('Killing Me Softly', 'Sarah Thompson', 'electronic');
insert into songs (Title, Artist, Genre) values ('My Heart Will Go On', 'Sarah Thompson', 'r&b');
insert into songs (Title, Artist, Genre) values ('Can''t Stop the Feeling!', 'Jessica Martinez', 'jazz');
insert into songs (Title, Artist, Genre) values ('My Heart Will Go On', 'John Smith', 'latin');
insert into songs (Title, Artist, Genre) values ('Every Breath You Take', 'Daniel Anderson', 'jazz');
insert into songs (Title, Artist, Genre) values ('Killing Me Softly', 'Jessica Martinez', 'dance');
insert into songs (Title, Artist, Genre) values ('Piano Man', 'Daniel Anderson', 'pop');
insert into songs (Title, Artist, Genre) values ('No Cry', 'Daniel Anderson', 'reggae');
insert into songs (Title, Artist, Genre) values ('Oops!... I Did It Again', 'Jessica Martinez', 'latin');
insert into songs (Title, Artist, Genre) values ('Shape of You', 'Daniel Anderson', 'r&b');
insert into songs (Title, Artist, Genre) values ('A Thousand Years', 'Olivia Taylor', 'blues');
insert into songs (Title, Artist, Genre) values ('No Cry', 'Christopher Thomas', 'blues');
insert into songs (Title, Artist, Genre) values ('No Cry', 'Sarah Thompson', 'electronic');
insert into songs (Title, Artist, Genre) values ('Let It Be', 'Sophia Hernandez', 'latin');
insert into songs (Title, Artist, Genre) values ('No Cry', 'Daniel Anderson', 'latin');
insert into songs (Title, Artist, Genre) values ('Let It Be', 'Olivia Taylor', 'electronic');
insert into songs (Title, Artist, Genre) values ('Piano Man', 'Christopher Thomas', 'pop');
insert into songs (Title, Artist, Genre) values ('Bohemian Rhapsody', 'Olivia Taylor', 'gospel');
insert into songs (Title, Artist, Genre) values ('Can''t Stop the Feeling!', 'Sophia Hernandez', 'punk');
insert into songs (Title, Artist, Genre) values ('Hallelujah', 'John Smith', 'dance');
insert into songs (Title, Artist, Genre) values ('No Woman', 'Sophia Hernandez', 'rap');
insert into songs (Title, Artist, Genre) values ('No Cry', 'David Wilson', 'indie');
insert into songs (Title, Artist, Genre) values ('Just the Way You Are', 'Jessica Martinez', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Just the Way You Are', 'Emily Johnson', 'reggae');
insert into songs (Title, Artist, Genre) values ('Killing Me Softly', 'Emily Johnson', 'alternative');
insert into songs (Title, Artist, Genre) values ('Bohemian Rhapsody', 'Emily Johnson', 'electronic');
insert into songs (Title, Artist, Genre) values ('Shape of You', 'John Smith', 'classical');
insert into songs (Title, Artist, Genre) values ('Piano Man', 'Daniel Anderson', 'country');
insert into songs (Title, Artist, Genre) values ('Rolling in the Deep', 'Sophia Hernandez', 'rock');
insert into songs (Title, Artist, Genre) values ('Just the Way You Are', 'Olivia Taylor', 'metal');
insert into songs (Title, Artist, Genre) values ('Grenade', 'Emily Johnson', 'reggae');
insert into songs (Title, Artist, Genre) values ('Just the Way You Are', 'Sarah Thompson', 'electronic');
insert into songs (Title, Artist, Genre) values ('Rolling in the Deep', 'David Wilson', 'gospel');
insert into songs (Title, Artist, Genre) values ('Oops!... I Did It Again', 'Christopher Thomas', 'gospel');
insert into songs (Title, Artist, Genre) values ('Bohemian Rhapsody', 'Daniel Anderson', 'country');
insert into songs (Title, Artist, Genre) values ('Just the Way You Are', 'Daniel Anderson', 'dance');
insert into songs (Title, Artist, Genre) values ('Piano Man', 'Michael Davis', 'gospel');
insert into songs (Title, Artist, Genre) values ('Every Breath You Take', 'Daniel Anderson', 'electronic');
insert into songs (Title, Artist, Genre) values ('Firework', 'Sarah Thompson', 'dance');
insert into songs (Title, Artist, Genre) values ('Killing Me Softly', 'Daniel Anderson', 'folk');
insert into songs (Title, Artist, Genre) values ('Shape of You', 'Daniel Anderson', 'metal');
insert into songs (Title, Artist, Genre) values ('Killing Me Softly', 'Christopher Thomas', 'soul');
insert into songs (Title, Artist, Genre) values ('Killing Me Softly', 'David Wilson', 'r&b');
insert into songs (Title, Artist, Genre) values ('Hallelujah', 'Emily Johnson', 'latin');
insert into songs (Title, Artist, Genre) values ('Killing Me Softly', 'Sophia Hernandez', 'country');
insert into songs (Title, Artist, Genre) values ('Firework', 'Christopher Thomas', 'gospel');
insert into songs (Title, Artist, Genre) values ('Bohemian Rhapsody', 'Daniel Anderson', 'classical');
insert into songs (Title, Artist, Genre) values ('Dancing Queen', 'Sarah Thompson', 'alternative');
insert into songs (Title, Artist, Genre) values ('Grenade', 'David Wilson', 'punk');
insert into songs (Title, Artist, Genre) values ('Let It Be', 'David Wilson', 'r&b');
insert into songs (Title, Artist, Genre) values ('Every Breath You Take', 'Christopher Thomas', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Oops!... I Did It Again', 'Sophia Hernandez', 'pop');
insert into songs (Title, Artist, Genre) values ('Thriller', 'Jessica Martinez', 'punk');
insert into songs (Title, Artist, Genre) values ('Piano Man', 'Michael Davis', 'metal');
insert into songs (Title, Artist, Genre) values ('Shape of You', 'Daniel Anderson', 'gospel');
insert into songs (Title, Artist, Genre) values ('Bohemian Rhapsody', 'Michael Davis', 'classical');
insert into songs (Title, Artist, Genre) values ('Uptown Funk', 'Daniel Anderson', 'blues');
insert into songs (Title, Artist, Genre) values ('A Thousand Years', 'John Smith', 'indie');
insert into songs (Title, Artist, Genre) values ('My Heart Will Go On', 'David Wilson', 'rock');
insert into songs (Title, Artist, Genre) values ('Dancing Queen', 'Michael Davis', 'metal');
insert into songs (Title, Artist, Genre) values ('Piano Man', 'Christopher Thomas', 'folk');
insert into songs (Title, Artist, Genre) values ('Dancing Queen', 'Daniel Anderson', 'folk');
insert into songs (Title, Artist, Genre) values ('Every Breath You Take', 'Christopher Thomas', 'metal');
insert into songs (Title, Artist, Genre) values ('No Cry', 'Sarah Thompson', 'pop');
insert into songs (Title, Artist, Genre) values ('Every Breath You Take', 'Daniel Anderson', 'gospel');
